namespace FlexKitTester.Components.Pages.ControlBenches;
public sealed record ControlBenchLink(string Name,string Route);
public static class ControlBenchCatalog { public static IReadOnlyList<ControlBenchLink> All {get;} = [
new("Popup","/flexcore-controls/popup"),
new("Tooltip","/flexcore-controls/tooltip"),
new("Popover","/flexcore-controls/popover"),
new("ButtonGroup","/flexcore-controls/button-group"),
new("Segmented","/flexcore-controls/segmented"),
new("Chip","/flexcore-controls/chip"),
new("ChipList","/flexcore-controls/chip-list"),
new("Avatar","/flexcore-controls/avatar"),
new("FloatingLabel","/flexcore-controls/floating-label"),
new("StackLayout","/flexcore-controls/stack-layout"),
new("AnimationContainer","/flexcore-controls/animation-container"),
new("MediaQuery","/flexcore-controls/media-query"),
new("Loader","/flexcore-controls/loader"),
new("LoaderContainer","/flexcore-controls/loader-container"),
new("ChunkProgressBar","/flexcore-controls/chunk-progress-bar"),
new("MaskedTextBox","/flexcore-controls/masked-text-box"),
new("RangeSlider","/flexcore-controls/range-slider"),
new("DateRangePicker","/flexcore-controls/date-range-picker"),
new("TreeView","/flexcore-controls/tree-view"),
new("TreeGrid","/flexcore-controls/tree-grid"),
new("TreeGrid operations","/flexcore-controls/tree-grid-operations"),
new("DropDownTree","/flexcore-controls/drop-down-tree"),
new("ColorGradient","/flexcore-controls/color-gradient"),
new("FlatColorPicker","/flexcore-controls/flat-color-picker"),
new("Signature","/flexcore-controls/signature"),
new("Upload","/flexcore-controls/upload"),
new("DropZone","/flexcore-controls/drop-zone"),
new("PromptBox","/flexcore-controls/prompt-box"),
new("Chat","/flexcore-controls/chat"),
new("InlineAIPrompt","/flexcore-controls/inline-ai-prompt"),
new("SmartPasteButton","/flexcore-controls/smart-paste-button"),
new("SpeechToTextButton","/flexcore-controls/speech-to-text-button"),
new("PDF Viewer","/flexcore-controls/pdf"),
new("Spreadsheet","/flexcore-controls/spreadsheet"),
new("EditorControl","/flexcore-controls/editor"),
new("Scheduler","/flexcore-controls/scheduler"),
new("Map","/flexcore-controls/map"),
];}
