//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace AutoNotice {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsAutoReports")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsAutoReports : global::System.Data.DataSet {
        
        private AutoNotice_GetAutoReportsListDataTable tableAutoNotice_GetAutoReportsList;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsAutoReports() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsAutoReports(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["AutoNotice_GetAutoReportsList"] != null)) {
                    base.Tables.Add(new AutoNotice_GetAutoReportsListDataTable(ds.Tables["AutoNotice_GetAutoReportsList"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public AutoNotice_GetAutoReportsListDataTable AutoNotice_GetAutoReportsList {
            get {
                return this.tableAutoNotice_GetAutoReportsList;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsAutoReports cln = ((dsAutoReports)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["AutoNotice_GetAutoReportsList"] != null)) {
                    base.Tables.Add(new AutoNotice_GetAutoReportsListDataTable(ds.Tables["AutoNotice_GetAutoReportsList"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableAutoNotice_GetAutoReportsList = ((AutoNotice_GetAutoReportsListDataTable)(base.Tables["AutoNotice_GetAutoReportsList"]));
            if ((initTable == true)) {
                if ((this.tableAutoNotice_GetAutoReportsList != null)) {
                    this.tableAutoNotice_GetAutoReportsList.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsAutoReports";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsAutoReports.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableAutoNotice_GetAutoReportsList = new AutoNotice_GetAutoReportsListDataTable();
            base.Tables.Add(this.tableAutoNotice_GetAutoReportsList);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeAutoNotice_GetAutoReportsList() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsAutoReports ds = new dsAutoReports();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void AutoNotice_GetAutoReportsListRowChangeEventHandler(object sender, AutoNotice_GetAutoReportsListRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class AutoNotice_GetAutoReportsListDataTable : global::System.Data.TypedTableBase<AutoNotice_GetAutoReportsListRow> {
            
            private global::System.Data.DataColumn columnSeq;
            
            private global::System.Data.DataColumn columnDescription;
            
            private global::System.Data.DataColumn columnRecipientAddress;
            
            private global::System.Data.DataColumn columnRecipientQuery;
            
            private global::System.Data.DataColumn columnFromAddress;
            
            private global::System.Data.DataColumn columnSubject;
            
            private global::System.Data.DataColumn columnMessage;
            
            private global::System.Data.DataColumn columnFrequencyType;
            
            private global::System.Data.DataColumn columnFrequencyValue;
            
            private global::System.Data.DataColumn columnTimeofDay;
            
            private global::System.Data.DataColumn columnNextRun;
            
            private global::System.Data.DataColumn columnAttachment;
            
            private global::System.Data.DataColumn columnReport;
            
            private global::System.Data.DataColumn columnParam1;
            
            private global::System.Data.DataColumn columnParam2;
            
            private global::System.Data.DataColumn columnParam3;
            
            private global::System.Data.DataColumn columnParam4;
            
            private global::System.Data.DataColumn columnParam5;
            
            private global::System.Data.DataColumn columnParam6;
            
            private global::System.Data.DataColumn columnParam7;
            
            private global::System.Data.DataColumn columnParam8;
            
            private global::System.Data.DataColumn columnParam9;
            
            private global::System.Data.DataColumn columnParam10;
            
            private global::System.Data.DataColumn columnFormattedSubject;
            
            private global::System.Data.DataColumn columnFormattedMessage;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public AutoNotice_GetAutoReportsListDataTable() {
                this.TableName = "AutoNotice_GetAutoReportsList";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal AutoNotice_GetAutoReportsListDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected AutoNotice_GetAutoReportsListDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SeqColumn {
                get {
                    return this.columnSeq;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DescriptionColumn {
                get {
                    return this.columnDescription;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RecipientAddressColumn {
                get {
                    return this.columnRecipientAddress;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RecipientQueryColumn {
                get {
                    return this.columnRecipientQuery;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FromAddressColumn {
                get {
                    return this.columnFromAddress;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SubjectColumn {
                get {
                    return this.columnSubject;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MessageColumn {
                get {
                    return this.columnMessage;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FrequencyTypeColumn {
                get {
                    return this.columnFrequencyType;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FrequencyValueColumn {
                get {
                    return this.columnFrequencyValue;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TimeofDayColumn {
                get {
                    return this.columnTimeofDay;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NextRunColumn {
                get {
                    return this.columnNextRun;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AttachmentColumn {
                get {
                    return this.columnAttachment;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ReportColumn {
                get {
                    return this.columnReport;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Param1Column {
                get {
                    return this.columnParam1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Param2Column {
                get {
                    return this.columnParam2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Param3Column {
                get {
                    return this.columnParam3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Param4Column {
                get {
                    return this.columnParam4;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Param5Column {
                get {
                    return this.columnParam5;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Param6Column {
                get {
                    return this.columnParam6;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Param7Column {
                get {
                    return this.columnParam7;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Param8Column {
                get {
                    return this.columnParam8;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Param9Column {
                get {
                    return this.columnParam9;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Param10Column {
                get {
                    return this.columnParam10;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FormattedSubjectColumn {
                get {
                    return this.columnFormattedSubject;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FormattedMessageColumn {
                get {
                    return this.columnFormattedMessage;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public AutoNotice_GetAutoReportsListRow this[int index] {
                get {
                    return ((AutoNotice_GetAutoReportsListRow)(this.Rows[index]));
                }
            }
            
            public event AutoNotice_GetAutoReportsListRowChangeEventHandler AutoNotice_GetAutoReportsListRowChanging;
            
            public event AutoNotice_GetAutoReportsListRowChangeEventHandler AutoNotice_GetAutoReportsListRowChanged;
            
            public event AutoNotice_GetAutoReportsListRowChangeEventHandler AutoNotice_GetAutoReportsListRowDeleting;
            
            public event AutoNotice_GetAutoReportsListRowChangeEventHandler AutoNotice_GetAutoReportsListRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddAutoNotice_GetAutoReportsListRow(AutoNotice_GetAutoReportsListRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public AutoNotice_GetAutoReportsListRow AddAutoNotice_GetAutoReportsListRow(
                        string Description, 
                        string RecipientAddress, 
                        string RecipientQuery, 
                        string FromAddress, 
                        string Subject, 
                        string Message, 
                        string FrequencyType, 
                        int FrequencyValue, 
                        System.DateTime TimeofDay, 
                        System.DateTime NextRun, 
                        string Attachment, 
                        string Report, 
                        string Param1, 
                        string Param2, 
                        string Param3, 
                        string Param4, 
                        string Param5, 
                        string Param6, 
                        string Param7, 
                        string Param8, 
                        string Param9, 
                        string Param10, 
                        string FormattedSubject, 
                        string FormattedMessage) {
                AutoNotice_GetAutoReportsListRow rowAutoNotice_GetAutoReportsListRow = ((AutoNotice_GetAutoReportsListRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        Description,
                        RecipientAddress,
                        RecipientQuery,
                        FromAddress,
                        Subject,
                        Message,
                        FrequencyType,
                        FrequencyValue,
                        TimeofDay,
                        NextRun,
                        Attachment,
                        Report,
                        Param1,
                        Param2,
                        Param3,
                        Param4,
                        Param5,
                        Param6,
                        Param7,
                        Param8,
                        Param9,
                        Param10,
                        FormattedSubject,
                        FormattedMessage};
                rowAutoNotice_GetAutoReportsListRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowAutoNotice_GetAutoReportsListRow);
                return rowAutoNotice_GetAutoReportsListRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public AutoNotice_GetAutoReportsListRow FindBySeq(int Seq) {
                return ((AutoNotice_GetAutoReportsListRow)(this.Rows.Find(new object[] {
                            Seq})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                AutoNotice_GetAutoReportsListDataTable cln = ((AutoNotice_GetAutoReportsListDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new AutoNotice_GetAutoReportsListDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnSeq = base.Columns["Seq"];
                this.columnDescription = base.Columns["Description"];
                this.columnRecipientAddress = base.Columns["RecipientAddress"];
                this.columnRecipientQuery = base.Columns["RecipientQuery"];
                this.columnFromAddress = base.Columns["FromAddress"];
                this.columnSubject = base.Columns["Subject"];
                this.columnMessage = base.Columns["Message"];
                this.columnFrequencyType = base.Columns["FrequencyType"];
                this.columnFrequencyValue = base.Columns["FrequencyValue"];
                this.columnTimeofDay = base.Columns["TimeofDay"];
                this.columnNextRun = base.Columns["NextRun"];
                this.columnAttachment = base.Columns["Attachment"];
                this.columnReport = base.Columns["Report"];
                this.columnParam1 = base.Columns["Param1"];
                this.columnParam2 = base.Columns["Param2"];
                this.columnParam3 = base.Columns["Param3"];
                this.columnParam4 = base.Columns["Param4"];
                this.columnParam5 = base.Columns["Param5"];
                this.columnParam6 = base.Columns["Param6"];
                this.columnParam7 = base.Columns["Param7"];
                this.columnParam8 = base.Columns["Param8"];
                this.columnParam9 = base.Columns["Param9"];
                this.columnParam10 = base.Columns["Param10"];
                this.columnFormattedSubject = base.Columns["FormattedSubject"];
                this.columnFormattedMessage = base.Columns["FormattedMessage"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnSeq = new global::System.Data.DataColumn("Seq", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSeq);
                this.columnDescription = new global::System.Data.DataColumn("Description", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescription);
                this.columnRecipientAddress = new global::System.Data.DataColumn("RecipientAddress", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRecipientAddress);
                this.columnRecipientQuery = new global::System.Data.DataColumn("RecipientQuery", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRecipientQuery);
                this.columnFromAddress = new global::System.Data.DataColumn("FromAddress", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFromAddress);
                this.columnSubject = new global::System.Data.DataColumn("Subject", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSubject);
                this.columnMessage = new global::System.Data.DataColumn("Message", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMessage);
                this.columnFrequencyType = new global::System.Data.DataColumn("FrequencyType", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFrequencyType);
                this.columnFrequencyValue = new global::System.Data.DataColumn("FrequencyValue", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFrequencyValue);
                this.columnTimeofDay = new global::System.Data.DataColumn("TimeofDay", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTimeofDay);
                this.columnNextRun = new global::System.Data.DataColumn("NextRun", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNextRun);
                this.columnAttachment = new global::System.Data.DataColumn("Attachment", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAttachment);
                this.columnReport = new global::System.Data.DataColumn("Report", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReport);
                this.columnParam1 = new global::System.Data.DataColumn("Param1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParam1);
                this.columnParam2 = new global::System.Data.DataColumn("Param2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParam2);
                this.columnParam3 = new global::System.Data.DataColumn("Param3", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParam3);
                this.columnParam4 = new global::System.Data.DataColumn("Param4", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParam4);
                this.columnParam5 = new global::System.Data.DataColumn("Param5", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParam5);
                this.columnParam6 = new global::System.Data.DataColumn("Param6", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParam6);
                this.columnParam7 = new global::System.Data.DataColumn("Param7", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParam7);
                this.columnParam8 = new global::System.Data.DataColumn("Param8", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParam8);
                this.columnParam9 = new global::System.Data.DataColumn("Param9", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParam9);
                this.columnParam10 = new global::System.Data.DataColumn("Param10", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParam10);
                this.columnFormattedSubject = new global::System.Data.DataColumn("FormattedSubject", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFormattedSubject);
                this.columnFormattedMessage = new global::System.Data.DataColumn("FormattedMessage", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFormattedMessage);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnSeq}, true));
                this.columnSeq.AutoIncrement = true;
                this.columnSeq.AllowDBNull = false;
                this.columnSeq.ReadOnly = true;
                this.columnSeq.Unique = true;
                this.columnDescription.MaxLength = 50;
                this.columnRecipientAddress.MaxLength = 500;
                this.columnFromAddress.MaxLength = 500;
                this.columnSubject.MaxLength = 200;
                this.columnFrequencyType.MaxLength = 50;
                this.columnAttachment.MaxLength = 500;
                this.columnReport.MaxLength = 500;
                this.columnParam1.MaxLength = 100;
                this.columnParam2.MaxLength = 100;
                this.columnParam3.MaxLength = 100;
                this.columnParam4.MaxLength = 100;
                this.columnParam5.MaxLength = 100;
                this.columnParam6.MaxLength = 100;
                this.columnParam7.MaxLength = 100;
                this.columnParam8.MaxLength = 100;
                this.columnParam9.MaxLength = 100;
                this.columnParam10.MaxLength = 100;
                this.columnFormattedSubject.MaxLength = 2000;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public AutoNotice_GetAutoReportsListRow NewAutoNotice_GetAutoReportsListRow() {
                return ((AutoNotice_GetAutoReportsListRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new AutoNotice_GetAutoReportsListRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(AutoNotice_GetAutoReportsListRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.AutoNotice_GetAutoReportsListRowChanged != null)) {
                    this.AutoNotice_GetAutoReportsListRowChanged(this, new AutoNotice_GetAutoReportsListRowChangeEvent(((AutoNotice_GetAutoReportsListRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.AutoNotice_GetAutoReportsListRowChanging != null)) {
                    this.AutoNotice_GetAutoReportsListRowChanging(this, new AutoNotice_GetAutoReportsListRowChangeEvent(((AutoNotice_GetAutoReportsListRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.AutoNotice_GetAutoReportsListRowDeleted != null)) {
                    this.AutoNotice_GetAutoReportsListRowDeleted(this, new AutoNotice_GetAutoReportsListRowChangeEvent(((AutoNotice_GetAutoReportsListRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.AutoNotice_GetAutoReportsListRowDeleting != null)) {
                    this.AutoNotice_GetAutoReportsListRowDeleting(this, new AutoNotice_GetAutoReportsListRowChangeEvent(((AutoNotice_GetAutoReportsListRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveAutoNotice_GetAutoReportsListRow(AutoNotice_GetAutoReportsListRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsAutoReports ds = new dsAutoReports();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "AutoNotice_GetAutoReportsListDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class AutoNotice_GetAutoReportsListRow : global::System.Data.DataRow {
            
            private AutoNotice_GetAutoReportsListDataTable tableAutoNotice_GetAutoReportsList;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal AutoNotice_GetAutoReportsListRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableAutoNotice_GetAutoReportsList = ((AutoNotice_GetAutoReportsListDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Seq {
                get {
                    return ((int)(this[this.tableAutoNotice_GetAutoReportsList.SeqColumn]));
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.SeqColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Description {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.DescriptionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Description\' in table \'AutoNotice_GetAutoReportsList\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.DescriptionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RecipientAddress {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.RecipientAddressColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RecipientAddress\' in table \'AutoNotice_GetAutoReportsList\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.RecipientAddressColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RecipientQuery {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.RecipientQueryColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RecipientQuery\' in table \'AutoNotice_GetAutoReportsList\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.RecipientQueryColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FromAddress {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.FromAddressColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FromAddress\' in table \'AutoNotice_GetAutoReportsList\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.FromAddressColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Subject {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.SubjectColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Subject\' in table \'AutoNotice_GetAutoReportsList\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.SubjectColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Message {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.MessageColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Message\' in table \'AutoNotice_GetAutoReportsList\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.MessageColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FrequencyType {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.FrequencyTypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FrequencyType\' in table \'AutoNotice_GetAutoReportsList\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.FrequencyTypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int FrequencyValue {
                get {
                    try {
                        return ((int)(this[this.tableAutoNotice_GetAutoReportsList.FrequencyValueColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FrequencyValue\' in table \'AutoNotice_GetAutoReportsList\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.FrequencyValueColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime TimeofDay {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableAutoNotice_GetAutoReportsList.TimeofDayColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TimeofDay\' in table \'AutoNotice_GetAutoReportsList\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.TimeofDayColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime NextRun {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableAutoNotice_GetAutoReportsList.NextRunColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NextRun\' in table \'AutoNotice_GetAutoReportsList\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.NextRunColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Attachment {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.AttachmentColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Attachment\' in table \'AutoNotice_GetAutoReportsList\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.AttachmentColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Report {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.ReportColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Report\' in table \'AutoNotice_GetAutoReportsList\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.ReportColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Param1 {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.Param1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Param1\' in table \'AutoNotice_GetAutoReportsList\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.Param1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Param2 {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.Param2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Param2\' in table \'AutoNotice_GetAutoReportsList\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.Param2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Param3 {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.Param3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Param3\' in table \'AutoNotice_GetAutoReportsList\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.Param3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Param4 {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.Param4Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Param4\' in table \'AutoNotice_GetAutoReportsList\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.Param4Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Param5 {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.Param5Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Param5\' in table \'AutoNotice_GetAutoReportsList\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.Param5Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Param6 {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.Param6Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Param6\' in table \'AutoNotice_GetAutoReportsList\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.Param6Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Param7 {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.Param7Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Param7\' in table \'AutoNotice_GetAutoReportsList\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.Param7Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Param8 {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.Param8Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Param8\' in table \'AutoNotice_GetAutoReportsList\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.Param8Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Param9 {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.Param9Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Param9\' in table \'AutoNotice_GetAutoReportsList\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.Param9Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Param10 {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.Param10Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Param10\' in table \'AutoNotice_GetAutoReportsList\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.Param10Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FormattedSubject {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.FormattedSubjectColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FormattedSubject\' in table \'AutoNotice_GetAutoReportsList\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.FormattedSubjectColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FormattedMessage {
                get {
                    try {
                        return ((string)(this[this.tableAutoNotice_GetAutoReportsList.FormattedMessageColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FormattedMessage\' in table \'AutoNotice_GetAutoReportsList\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableAutoNotice_GetAutoReportsList.FormattedMessageColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDescriptionNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.DescriptionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDescriptionNull() {
                this[this.tableAutoNotice_GetAutoReportsList.DescriptionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRecipientAddressNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.RecipientAddressColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRecipientAddressNull() {
                this[this.tableAutoNotice_GetAutoReportsList.RecipientAddressColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRecipientQueryNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.RecipientQueryColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRecipientQueryNull() {
                this[this.tableAutoNotice_GetAutoReportsList.RecipientQueryColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFromAddressNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.FromAddressColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFromAddressNull() {
                this[this.tableAutoNotice_GetAutoReportsList.FromAddressColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSubjectNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.SubjectColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSubjectNull() {
                this[this.tableAutoNotice_GetAutoReportsList.SubjectColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMessageNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.MessageColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMessageNull() {
                this[this.tableAutoNotice_GetAutoReportsList.MessageColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFrequencyTypeNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.FrequencyTypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFrequencyTypeNull() {
                this[this.tableAutoNotice_GetAutoReportsList.FrequencyTypeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFrequencyValueNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.FrequencyValueColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFrequencyValueNull() {
                this[this.tableAutoNotice_GetAutoReportsList.FrequencyValueColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTimeofDayNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.TimeofDayColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTimeofDayNull() {
                this[this.tableAutoNotice_GetAutoReportsList.TimeofDayColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNextRunNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.NextRunColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNextRunNull() {
                this[this.tableAutoNotice_GetAutoReportsList.NextRunColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAttachmentNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.AttachmentColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAttachmentNull() {
                this[this.tableAutoNotice_GetAutoReportsList.AttachmentColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsReportNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.ReportColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetReportNull() {
                this[this.tableAutoNotice_GetAutoReportsList.ReportColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsParam1Null() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.Param1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetParam1Null() {
                this[this.tableAutoNotice_GetAutoReportsList.Param1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsParam2Null() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.Param2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetParam2Null() {
                this[this.tableAutoNotice_GetAutoReportsList.Param2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsParam3Null() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.Param3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetParam3Null() {
                this[this.tableAutoNotice_GetAutoReportsList.Param3Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsParam4Null() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.Param4Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetParam4Null() {
                this[this.tableAutoNotice_GetAutoReportsList.Param4Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsParam5Null() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.Param5Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetParam5Null() {
                this[this.tableAutoNotice_GetAutoReportsList.Param5Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsParam6Null() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.Param6Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetParam6Null() {
                this[this.tableAutoNotice_GetAutoReportsList.Param6Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsParam7Null() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.Param7Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetParam7Null() {
                this[this.tableAutoNotice_GetAutoReportsList.Param7Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsParam8Null() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.Param8Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetParam8Null() {
                this[this.tableAutoNotice_GetAutoReportsList.Param8Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsParam9Null() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.Param9Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetParam9Null() {
                this[this.tableAutoNotice_GetAutoReportsList.Param9Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsParam10Null() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.Param10Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetParam10Null() {
                this[this.tableAutoNotice_GetAutoReportsList.Param10Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFormattedSubjectNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.FormattedSubjectColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFormattedSubjectNull() {
                this[this.tableAutoNotice_GetAutoReportsList.FormattedSubjectColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFormattedMessageNull() {
                return this.IsNull(this.tableAutoNotice_GetAutoReportsList.FormattedMessageColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFormattedMessageNull() {
                this[this.tableAutoNotice_GetAutoReportsList.FormattedMessageColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class AutoNotice_GetAutoReportsListRowChangeEvent : global::System.EventArgs {
            
            private AutoNotice_GetAutoReportsListRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public AutoNotice_GetAutoReportsListRowChangeEvent(AutoNotice_GetAutoReportsListRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public AutoNotice_GetAutoReportsListRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591